use std::env;
use std::fs;
use std::path::Path;

const ENV_FILE: &str = ".env";

#[derive(Debug, Clone)]
pub struct Config {
    pub database_url: Option<String>,
    pub jwt_secret: String,
    pub port: u16,
    pub data_dir: String,
    pub storage_root: String,
    pub anon_key: String,
    pub service_key: String,
    pub log_level: String,   // SUPARUST_LOG_LEVEL
    pub log_format: String,  // SUPARUST_LOG_FORMAT: "pretty" | "json"
    pub env: String,         // SUPARUST_ENV, default "local"
    pub pid_file: String,    // derived from env+port, or SUPARUST_PID_FILE override
}

impl Config {
    pub fn from_env() -> Self {
        // Priority 1: .env file (ignore if not found)
        dotenvy::dotenv().ok();

        // Priority 2: SUPARUST_* env vars -> Priority 3: legacy names -> Priority 4: auto-generate
        let jwt_secret_opt = env::var("SUPARUST_JWT_SECRET").or_else(|_| env::var("JWT_SECRET"));

        let jwt_secret = match jwt_secret_opt {
            Ok(secret) => secret,
            Err(_) => {
                eprintln!("warning: No JWT secret found. Auto-generating securely to .env file...");
                load_or_generate_env()
            }
        };

        // Reload .env in case it was just generated/appended
        dotenvy::dotenv().ok();

        let anon_key = env::var("SUPARUST_ANON_KEY")
            .unwrap_or_else(|_| generate_jwt(&jwt_secret, "anon"));

        let service_key = env::var("SUPARUST_SERVICE_KEY")
            .unwrap_or_else(|_| generate_jwt(&jwt_secret, "service_role"));

        // Validate log_format early — fail fast rather than panic deep in init_tracing
        let log_format = env::var("SUPARUST_LOG_FORMAT").unwrap_or_else(|_| "pretty".to_string());
        if log_format != "pretty" && log_format != "json" {
            eprintln!(
                "error: SUPARUST_LOG_FORMAT=\"{}\" is invalid. Valid values: \"pretty\", \"json\"",
                log_format
            );
            std::process::exit(1);
        }

        // Parse port with explicit warning on invalid value
        let port = env::var("SUPARUST_PORT")
            .or_else(|_| env::var("PORT"))
            .ok()
            .and_then(|p| {
                p.parse::<u16>().map_err(|_| {
                    eprintln!(
                        "warning: SUPARUST_PORT=\"{}\" is not a valid port number. Falling back to 3000.",
                        p
                    );
                }).ok()
            })
            .unwrap_or(3000);

        let env_name = env::var("SUPARUST_ENV")
            .unwrap_or_else(|_| "local".to_string());

        let pid_file = env::var("SUPARUST_PID_FILE")
            .unwrap_or_else(|_| format!(".suparust.{}.{}.pid", env_name, port));

        Self {
            database_url: env::var("SUPARUST_DB_URL")
                .or_else(|_| env::var("DATABASE_URL"))
                .ok(),
            jwt_secret,
            port,
            data_dir: env::var("SUPARUST_DB_DATA_DIR")
                .or_else(|_| env::var("DATA_DIR"))
                .unwrap_or_else(|_| "./data/postgres".to_string()),
            storage_root: env::var("SUPARUST_STORAGE_ROOT")
                .or_else(|_| env::var("STORAGE_ROOT"))
                .unwrap_or_else(|_| "./data/storage".to_string()),
            anon_key,
            service_key,
            log_level: env::var("SUPARUST_LOG_LEVEL").unwrap_or_else(|_| "info".to_string()),
            log_format,
            env: env_name,
            pid_file,
        }
    }
}

fn load_or_generate_env() -> String {
    let secret = generate_secret();
    let anon_init = generate_jwt(&secret, "anon");
    let service_init = generate_jwt(&secret, "service_role");

    // Print keys only at generation time — not on every subsequent startup
    eprintln!("info:  Generated new credentials. Copy these to your .env:");
    eprintln!("info:  SUPARUST_JWT_SECRET={}", secret);
    eprintln!("info:  SUPARUST_ANON_KEY={}", anon_init);
    eprintln!("info:  SUPARUST_SERVICE_KEY={}", service_init);

    let env_content = format!(
        "\n# Auto-generated by SupaRust\n\
        SUPARUST_JWT_SECRET={secret}\n\
        SUPARUST_ANON_KEY={anon_init}\n\
        SUPARUST_SERVICE_KEY={service_init}\n"
    );

    if Path::new(ENV_FILE).exists() {
        // .env exists but missing secret -> append
        let _ = fs::OpenOptions::new()
            .append(true)
            .open(ENV_FILE)
            .and_then(|mut f| { use std::io::Write; f.write_all(env_content.as_bytes()) });
        eprintln!("info:  Appended missing keys to existing .env");
    } else {
        // completely fresh
        let full_content = format!(
            "# SupaRust Environment\n\
            SUPARUST_PORT=3000\n\
            SUPARUST_DB_DATA_DIR=./data/postgres\n\
            SUPARUST_STORAGE_ROOT=./data/storage\n\
            SUPARUST_LOG_LEVEL=info\n\
            SUPARUST_LOG_FORMAT=pretty\n\
            {env_content}"
        );
        let _ = fs::write(ENV_FILE, full_content);
        eprintln!("info:  Generated fresh .env with new keys");
    }

    secret
}

/// Generate a cryptographically secure 32-byte random secret, hex-encoded.
fn generate_secret() -> String {
    use rand::RngCore;
    use rand::rngs::OsRng;
    let mut bytes = [0u8; 32];
    OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// Generate HS256 JWT with standard claims for anon / service_role.
/// Includes exp = 10 years from now to satisfy strict JWT validators.
fn generate_jwt(secret: &str, role: &str) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};

    let iat = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let exp = iat + 10 * 365 * 24 * 3600; // 10 years

    let header = base64_url_encode(br#"{"alg":"HS256","typ":"JWT"}"#);
    let payload = base64_url_encode(
        format!(
            r#"{{"role":"{}","iss":"suparust","iat":{},"exp":{}}}"#,
            role, iat, exp
        )
        .as_bytes(),
    );

    let signing_input = format!("{}.{}", header, payload);
    let signature = hmac_sha256_sign(secret.as_bytes(), signing_input.as_bytes());
    let sig_encoded = base64_url_encode(&signature);

    format!("{}.{}.{}", header, payload, sig_encoded)
}

fn base64_url_encode(input: &[u8]) -> String {
    use std::fmt::Write;
    let b64 = BASE64_TABLE;
    let mut out = String::new();
    let mut i = 0;
    while i + 2 < input.len() {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8) | (input[i + 2] as u32);
        let _ = write!(out, "{}{}{}{}",
            b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize],
            b64[((n >> 6) & 0x3F) as usize], b64[(n & 0x3F) as usize]);
        i += 3;
    }
    if i + 1 == input.len() {
        let n = (input[i] as u32) << 16;
        let _ = write!(out, "{}{}", b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize]);
    } else if i + 2 == input.len() {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8);
        let _ = write!(out, "{}{}{}",
            b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize], b64[((n >> 6) & 0x3F) as usize]);
    }
    out
}

const BASE64_TABLE: &[char] = &[
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P',
    'Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f',
    'g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v',
    'w','x','y','z','0','1','2','3','4','5','6','7','8','9','-','_',
];

fn hmac_sha256_sign(key: &[u8], data: &[u8]) -> Vec<u8> {
    use sha2::Digest;
    const BLOCK_SIZE: usize = 64;
    let mut k = if key.len() > BLOCK_SIZE {
        let mut h = sha2::Sha256::new();
        h.update(key);
        h.finalize().to_vec()
    } else {
        key.to_vec()
    };
    k.resize(BLOCK_SIZE, 0);

    let i_key: Vec<u8> = k.iter().map(|b| b ^ 0x36).collect();
    let o_key: Vec<u8> = k.iter().map(|b| b ^ 0x5C).collect();

    let mut inner = sha2::Sha256::new();
    inner.update(&i_key);
    inner.update(data);
    let inner_hash = inner.finalize();

    let mut outer = sha2::Sha256::new();
    outer.update(&o_key);
    outer.update(&inner_hash);
    outer.finalize().to_vec()
}
