use std::env;
use std::fs;
use std::path::Path;

const ENV_FILE: &str = ".env";

#[derive(Debug, Clone)]
pub struct Config {
    pub database_url: Option<String>,
    pub jwt_secret: String,
    pub port: u16,
    pub data_dir: String,
    pub storage_root: String,
    pub anon_key: String,
    pub service_key: String,
    pub log_level: String,   // SUPARUST_LOG_LEVEL
    pub log_format: String,  // SUPARUST_LOG_FORMAT
}

impl Config {
    pub fn from_env() -> Self {
        // Priority 1: .env file (ignore if not found)
        dotenvy::dotenv().ok();

        // Priority 2: SUPARUST_* env vars -> Priority 3: legacy names -> Priority 4: auto-generate
        let jwt_secret_opt = env::var("SUPARUST_JWT_SECRET").or_else(|_| env::var("JWT_SECRET"));

        let jwt_secret = match jwt_secret_opt {
            Ok(secret) => secret,
            Err(_) => {
                tracing::warn!("No JWT Secret found. Auto-generating securely to .env file...");
                load_or_generate_env()
            }
        };

        // Reload .env in case it was just generated/appended
        dotenvy::dotenv().ok();

        let anon_key = env::var("SUPARUST_ANON_KEY")
            .unwrap_or_else(|_| generate_jwt(&jwt_secret, "anon"));

        let service_key = env::var("SUPARUST_SERVICE_KEY")
            .unwrap_or_else(|_| generate_jwt(&jwt_secret, "service_role"));

        // Print keys on startup so developer can copy to .env
        tracing::info!("ANON_KEY:    {}", anon_key);
        tracing::info!("SERVICE_KEY: {}", service_key);

        Self {
            database_url: env::var("SUPARUST_DB_URL")
                .or_else(|_| env::var("DATABASE_URL"))
                .ok(),
            jwt_secret,
            port: env::var("SUPARUST_PORT")
                .or_else(|_| env::var("PORT"))
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(3000),
            data_dir: env::var("SUPARUST_DB_DATA_DIR")
                .or_else(|_| env::var("DATA_DIR"))
                .unwrap_or_else(|_| "./data/postgres".to_string()),
            storage_root: env::var("SUPARUST_STORAGE_ROOT")
                .or_else(|_| env::var("STORAGE_ROOT"))
                .unwrap_or_else(|_| "./data/storage".to_string()),
            anon_key,
            service_key,
            log_level: env::var("SUPARUST_LOG_LEVEL")
                .unwrap_or_else(|_| "info".to_string()),
            log_format: env::var("SUPARUST_LOG_FORMAT")
                .unwrap_or_else(|_| "pretty".to_string()),
        }
    }
}

fn load_or_generate_env() -> String {
    let secret = generate_secret();
    let anon_init = generate_jwt(&secret, "anon");
    let service_init = generate_jwt(&secret, "service_role");

    let env_content = format!(
        "\n# Auto-generated by SupaRust\n\
        SUPARUST_JWT_SECRET={secret}\n\
        SUPARUST_ANON_KEY={anon_init}\n\
        SUPARUST_SERVICE_KEY={service_init}\n"
    );

    if Path::new(ENV_FILE).exists() {
        // .env exists but missing secret -> append
        let _ = fs::OpenOptions::new()
            .append(true)
            .open(ENV_FILE)
            .and_then(|mut f| { use std::io::Write; f.write_all(env_content.as_bytes()) });
        tracing::info!("Appended missing keys to existing .env");
    } else {
        // completely fresh
        let full_content = format!(
            "# SupaRust Environment\n\
            SUPARUST_PORT=3000\n\
            SUPARUST_DB_DATA_DIR=./data/postgres\n\
            SUPARUST_STORAGE_ROOT=./data/storage\n\
            SUPARUST_LOG_LEVEL=info\n\
            SUPARUST_LOG_FORMAT=pretty\n\
            {env_content}"
        );
        let _ = fs::write(ENV_FILE, full_content);
        tracing::info!("Generated fresh .env with new keys");
    }

    secret
}

fn generate_secret() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let hash_string = format!("{:x}some_salt_for_generating_secret_like_this", now);
    hex::encode(hash_string)
}

/// Generate HS256 JWT dengan claim minimal untuk anon / service_role
fn generate_jwt(secret: &str, role: &str) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};

    let iat = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();

    let header = base64_url_encode(br#"{"alg":"HS256","typ":"JWT"}"#);
    let payload = base64_url_encode(
        format!(r#"{{"role":"{}","iss":"suparust","iat":{}}}"#, role, iat).as_bytes(),
    );

    let signing_input = format!("{}.{}", header, payload);
    let signature = hmac_sha256_sign(secret.as_bytes(), signing_input.as_bytes());
    let sig_encoded = base64_url_encode(&signature);

    format!("{}.{}.{}", header, payload, sig_encoded)
}

fn base64_url_encode(input: &[u8]) -> String {
    use std::fmt::Write;
    let b64 = BASE64_TABLE;
    let mut out = String::new();
    let mut i = 0;
    while i + 2 < input.len() {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8) | (input[i + 2] as u32);
        let _ = write!(out, "{}{}{}{}",
            b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize],
            b64[((n >> 6) & 0x3F) as usize], b64[(n & 0x3F) as usize]);
        i += 3;
    }
    if i + 1 == input.len() {
        let n = (input[i] as u32) << 16;
        let _ = write!(out, "{}{}", b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize]);
    } else if i + 2 == input.len() {
        let n = ((input[i] as u32) << 16) | ((input[i + 1] as u32) << 8);
        let _ = write!(out, "{}{}{}",
            b64[(n >> 18) as usize], b64[((n >> 12) & 0x3F) as usize], b64[((n >> 6) & 0x3F) as usize]);
    }
    out
}

const BASE64_TABLE: &[char] = &[
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P',
    'Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f',
    'g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v',
    'w','x','y','z','0','1','2','3','4','5','6','7','8','9','-','_',
];

fn hmac_sha256_sign(key: &[u8], data: &[u8]) -> Vec<u8> {
    use sha2::Digest;
    const BLOCK_SIZE: usize = 64;
    let mut k = if key.len() > BLOCK_SIZE {
        let mut h = sha2::Sha256::new();
        h.update(key);
        h.finalize().to_vec()
    } else {
        key.to_vec()
    };
    k.resize(BLOCK_SIZE, 0);

    let i_key: Vec<u8> = k.iter().map(|b| b ^ 0x36).collect();
    let o_key: Vec<u8> = k.iter().map(|b| b ^ 0x5C).collect();

    let mut inner = sha2::Sha256::new();
    inner.update(&i_key);
    inner.update(data);
    let inner_hash = inner.finalize();

    let mut outer = sha2::Sha256::new();
    outer.update(&o_key);
    outer.update(&inner_hash);
    outer.finalize().to_vec()
}
